image: mcr.microsoft.com/dotnet/core/sdk:2.1

stages:
    - build
    - test

variables:
    BuildConfiguration: "Release"

build:
    stage: build
    script:
        - "cd app"
        - "dotnet restore"
        - "dotnet build --configuration $BuildConfiguration"
    artifacts:
        paths:
            - app/bin/
            - app/obj/

test:
    stage: test
    script:
        - "cd tests"
        - "dotnet restore"
        - "dotnet test  --configuration $BuildConfiguration"

